// Maps common/colloquial job titles to O*NET standardized occupation titles
// This enables fuzzy matching when users search for titles that don't exactly match O*NET taxonomy

export const JOB_ALIASES: Record<string, string[]> = {
  // Management & Executive
  "account manager": ["Sales Managers", "Advertising Sales Agents", "Sales Representatives"],
  "key account manager": ["Sales Managers", "Advertising Sales Agents"],
  "account executive": ["Sales Managers", "Advertising Sales Agents", "Sales Representatives"],
  "business development": ["Sales Managers", "Marketing Managers", "Management Analysts"],
  "biz dev": ["Sales Managers", "Marketing Managers", "Management Analysts"],
  "ceo": ["Chief Executives"],
  "cto": ["Computer and Information Systems Managers", "Chief Executives"],
  "cfo": ["Financial Managers", "Chief Executives"],
  "coo": ["General and Operations Managers", "Chief Executives"],
  "cmo": ["Marketing Managers", "Advertising and Promotions Managers"],
  "cio": ["Computer and Information Systems Managers"],
  "vp": ["General and Operations Managers", "Chief Executives"],
  "vice president": ["General and Operations Managers", "Chief Executives"],
  "director": ["General and Operations Managers", "Managers, All Other"],
  "managing director": ["General and Operations Managers", "Chief Executives"],
  "team lead": ["First-Line Supervisors", "General and Operations Managers"],
  "team leader": ["First-Line Supervisors", "General and Operations Managers"],
  "office manager": ["Administrative Services Managers", "First-Line Supervisors of Office and Administrative Support Workers"],
  "branch manager": ["General and Operations Managers", "Financial Managers"],
  "store manager": ["First-Line Supervisors of Retail Sales Workers", "General and Operations Managers"],
  "restaurant manager": ["Food Service Managers"],
  "bar manager": ["Food Service Managers"],
  "hotel manager": ["Lodging Managers"],
  "warehouse manager": ["Transportation, Storage, and Distribution Managers"],

  // Tech & Software
  "software engineer": ["Software Developers", "Software Quality Assurance Analysts and Testers"],
  "software developer": ["Software Developers"],
  "web developer": ["Web Developers", "Web and Digital Interface Designers"],
  "frontend developer": ["Web Developers", "Web and Digital Interface Designers"],
  "front-end developer": ["Web Developers", "Web and Digital Interface Designers"],
  "backend developer": ["Software Developers", "Database Architects"],
  "back-end developer": ["Software Developers", "Database Architects"],
  "full stack developer": ["Software Developers", "Web Developers"],
  "fullstack developer": ["Software Developers", "Web Developers"],
  "mobile developer": ["Software Developers"],
  "app developer": ["Software Developers"],
  "ios developer": ["Software Developers"],
  "android developer": ["Software Developers"],
  "devops": ["Software Developers", "Network and Computer Systems Administrators", "Computer Systems Engineers/Architects"],
  "devops engineer": ["Software Developers", "Network and Computer Systems Administrators"],
  "sre": ["Software Developers", "Network and Computer Systems Administrators"],
  "site reliability": ["Software Developers", "Network and Computer Systems Administrators"],
  "cloud engineer": ["Network and Computer Systems Administrators", "Computer Systems Engineers/Architects"],
  "data engineer": ["Software Developers", "Data Warehousing Specialists", "Database Architects"],
  "ml engineer": ["Software Developers", "Data Scientists", "Computer and Information Research Scientists"],
  "machine learning": ["Data Scientists", "Computer and Information Research Scientists", "Software Developers"],
  "ai engineer": ["Software Developers", "Data Scientists", "Computer and Information Research Scientists"],
  "data scientist": ["Data Scientists"],
  "data analyst": ["Business Intelligence Analysts", "Data Scientists", "Operations Research Analysts"],
  "business analyst": ["Business Intelligence Analysts", "Management Analysts", "Operations Research Analysts"],
  "systems analyst": ["Computer Systems Analysts"],
  "qa engineer": ["Software Quality Assurance Analysts and Testers"],
  "qa tester": ["Software Quality Assurance Analysts and Testers"],
  "quality assurance": ["Software Quality Assurance Analysts and Testers"],
  "test engineer": ["Software Quality Assurance Analysts and Testers"],
  "programmer": ["Computer Programmers", "Software Developers"],
  "coder": ["Computer Programmers", "Software Developers"],
  "it manager": ["Computer and Information Systems Managers"],
  "it director": ["Computer and Information Systems Managers"],
  "it support": ["Computer User Support Specialists", "Computer Network Support Specialists"],
  "it specialist": ["Computer User Support Specialists", "Computer Occupations, All Other"],
  "tech support": ["Computer User Support Specialists", "Computer Network Support Specialists"],
  "help desk": ["Computer User Support Specialists"],
  "sysadmin": ["Network and Computer Systems Administrators"],
  "system administrator": ["Network and Computer Systems Administrators"],
  "network engineer": ["Computer Network Architects", "Network and Computer Systems Administrators"],
  "network admin": ["Network and Computer Systems Administrators"],
  "dba": ["Database Administrators", "Database Architects"],
  "database admin": ["Database Administrators"],
  "infosec": ["Information Security Analysts", "Information Security Engineers"],
  "cybersecurity": ["Information Security Analysts", "Information Security Engineers"],
  "security analyst": ["Information Security Analysts"],
  "penetration tester": ["Penetration Testers"],
  "ethical hacker": ["Penetration Testers"],
  "scrum master": ["Project Management Specialists", "Information Technology Project Managers"],
  "product manager": ["Project Management Specialists", "Marketing Managers"],
  "product owner": ["Project Management Specialists", "Marketing Managers"],
  "project manager": ["Project Management Specialists", "Information Technology Project Managers"],
  "program manager": ["Project Management Specialists", "General and Operations Managers"],
  "ux designer": ["Web and Digital Interface Designers"],
  "ui designer": ["Web and Digital Interface Designers"],
  "ux/ui designer": ["Web and Digital Interface Designers"],
  "ui/ux designer": ["Web and Digital Interface Designers"],
  "graphic designer": ["Graphic Designers"],
  "web designer": ["Web and Digital Interface Designers", "Graphic Designers"],
  "blockchain developer": ["Blockchain Engineers", "Software Developers"],
  "crypto developer": ["Blockchain Engineers", "Software Developers"],

  // Finance & Accounting
  "accountant": ["Accountants and Auditors"],
  "auditor": ["Accountants and Auditors"],
  "bookkeeper": ["Bookkeeping, Accounting, and Auditing Clerks"],
  "controller": ["Treasurers and Controllers"],
  "treasurer": ["Treasurers and Controllers"],
  "financial analyst": ["Financial and Investment Analysts", "Financial Quantitative Analysts"],
  "investment banker": ["Securities, Commodities, and Financial Services Sales Agents", "Financial and Investment Analysts"],
  "banker": ["Loan Officers", "Financial Managers", "Tellers"],
  "bank teller": ["Tellers"],
  "loan officer": ["Loan Officers"],
  "mortgage broker": ["Loan Officers"],
  "financial advisor": ["Personal Financial Advisors"],
  "financial planner": ["Personal Financial Advisors"],
  "wealth manager": ["Personal Financial Advisors", "Investment Fund Managers"],
  "portfolio manager": ["Investment Fund Managers", "Financial and Investment Analysts"],
  "fund manager": ["Investment Fund Managers"],
  "trader": ["Securities, Commodities, and Financial Services Sales Agents"],
  "stock broker": ["Securities, Commodities, and Financial Services Sales Agents"],
  "actuary": ["Actuaries"],
  "underwriter": ["Insurance Underwriters"],
  "claims adjuster": ["Claims Adjusters, Examiners, and Investigators"],
  "tax preparer": ["Tax Preparers"],
  "tax accountant": ["Accountants and Auditors", "Tax Preparers"],
  "credit analyst": ["Credit Analysts"],
  "risk analyst": ["Financial Risk Specialists"],

  // Sales & Marketing
  "salesperson": ["Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products", "Retail Salespersons"],
  "sales rep": ["Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products", "Sales Representatives of Services"],
  "sales representative": ["Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products"],
  "sales associate": ["Retail Salespersons"],
  "retail associate": ["Retail Salespersons"],
  "cashier": ["Cashiers"],
  "marketer": ["Market Research Analysts and Marketing Specialists", "Marketing Managers"],
  "marketing specialist": ["Market Research Analysts and Marketing Specialists"],
  "digital marketer": ["Market Research Analysts and Marketing Specialists", "Search Marketing Strategists"],
  "seo specialist": ["Search Marketing Strategists"],
  "seo manager": ["Search Marketing Strategists", "Marketing Managers"],
  "content marketer": ["Market Research Analysts and Marketing Specialists", "Technical Writers"],
  "social media manager": ["Public Relations Specialists", "Market Research Analysts and Marketing Specialists"],
  "social media specialist": ["Public Relations Specialists", "Market Research Analysts and Marketing Specialists"],
  "community manager": ["Public Relations Specialists"],
  "pr specialist": ["Public Relations Specialists"],
  "public relations": ["Public Relations Specialists", "Public Relations Managers"],
  "copywriter": ["Writers and Authors"],
  "content writer": ["Writers and Authors", "Technical Writers"],
  "ad sales": ["Advertising Sales Agents"],
  "media buyer": ["Advertising and Promotions Managers", "Advertising Sales Agents"],
  "brand manager": ["Marketing Managers", "Advertising and Promotions Managers"],
  "ecommerce manager": ["Online Merchants", "Marketing Managers"],
  "real estate agent": ["Real Estate Sales Agents"],
  "realtor": ["Real Estate Sales Agents", "Real Estate Brokers"],
  "insurance agent": ["Insurance Sales Agents"],
  "travel agent": ["Travel Agents"],

  // HR & People
  "hr manager": ["Human Resources Managers"],
  "hr specialist": ["Human Resources Specialists"],
  "hr coordinator": ["Human Resources Specialists", "Human Resources Assistants, Except Payroll and Timekeeping"],
  "hr director": ["Human Resources Managers"],
  "human resources": ["Human Resources Managers", "Human Resources Specialists"],
  "recruiter": ["Human Resources Specialists"],
  "talent acquisition": ["Human Resources Specialists"],
  "headhunter": ["Human Resources Specialists"],
  "payroll specialist": ["Payroll and Timekeeping Clerks"],
  "payroll clerk": ["Payroll and Timekeeping Clerks"],
  "benefits coordinator": ["Compensation, Benefits, and Job Analysis Specialists"],
  "training manager": ["Training and Development Managers"],
  "training specialist": ["Training and Development Specialists"],
  "l&d specialist": ["Training and Development Specialists"],
  "learning and development": ["Training and Development Specialists", "Training and Development Managers"],

  // Healthcare
  "doctor": ["Physicians, All Other", "Family Medicine Physicians", "General Internal Medicine Physicians"],
  "physician": ["Physicians, All Other", "Family Medicine Physicians"],
  "surgeon": ["Surgeons, All Other"],
  "nurse": ["Registered Nurses"],
  "rn": ["Registered Nurses"],
  "lpn": ["Licensed Practical and Licensed Vocational Nurses"],
  "nurse practitioner": ["Nurse Practitioners"],
  "np": ["Nurse Practitioners"],
  "pa": ["Physician Assistants"],
  "physician assistant": ["Physician Assistants"],
  "dentist": ["Dentists, General"],
  "dental hygienist": ["Dental Hygienists"],
  "pharmacist": ["Pharmacists"],
  "pharmacy tech": ["Pharmacy Technicians"],
  "physical therapist": ["Physical Therapists"],
  "pt": ["Physical Therapists"],
  "occupational therapist": ["Occupational Therapists"],
  "ot": ["Occupational Therapists"],
  "paramedic": ["Paramedics"],
  "emt": ["Emergency Medical Technicians"],
  "medical assistant": ["Medical Assistants"],
  "cna": ["Nursing Assistants"],
  "therapist": ["Mental Health Counselors", "Psychologists, All Other", "Marriage and Family Therapists"],
  "psychologist": ["Psychologists, All Other", "Clinical and Counseling Psychologists"],
  "psychiatrist": ["Psychiatrists"],
  "counselor": ["Mental Health Counselors", "Substance Abuse, Behavioral Disorder, and Mental Health Counselors"],
  "social worker": ["Child, Family, and School Social Workers", "Healthcare Social Workers"],
  "veterinarian": ["Veterinarians"],
  "vet": ["Veterinarians"],
  "vet tech": ["Veterinary Technologists and Technicians"],
  "optometrist": ["Optometrists"],
  "chiropractor": ["Chiropractors"],
  "radiologist": ["Physicians, All Other"],
  "anesthesiologist": ["Anesthesiologists"],
  "cardiologist": ["Cardiologists"],
  "dermatologist": ["Dermatologists"],
  "pediatrician": ["Pediatricians, General"],

  // Legal
  "lawyer": ["Lawyers"],
  "attorney": ["Lawyers"],
  "paralegal": ["Paralegals and Legal Assistants"],
  "legal assistant": ["Paralegals and Legal Assistants", "Legal Secretaries and Administrative Assistants"],
  "judge": ["Judges, Magistrate Judges, and Magistrates"],
  "compliance officer": ["Compliance Officers"],
  "compliance manager": ["Compliance Managers"],

  // Education
  "teacher": ["Elementary School Teachers, Except Special Education", "Secondary School Teachers, Except Special and Career/Technical Education", "Middle School Teachers, Except Special and Career/Technical Education"],
  "professor": ["Postsecondary Teachers, All Other"],
  "tutor": ["Tutors"],
  "substitute teacher": ["Substitute Teachers, Short-Term"],
  "teaching assistant": ["Teaching Assistants, All Other"],
  "ta": ["Teaching Assistants, All Other", "Teaching Assistants, Postsecondary"],
  "principal": ["Education Administrators, Kindergarten through Secondary"],
  "school counselor": ["Educational, Guidance, and Career Counselors and Advisors"],
  "librarian": ["Librarians and Media Collections Specialists"],
  "instructor": ["Instructors and Teachers, All Other", "Self-Enrichment Teachers"],

  // Admin & Office
  "secretary": ["Secretaries and Administrative Assistants, Except Legal, Medical, and Executive"],
  "admin assistant": ["Secretaries and Administrative Assistants, Except Legal, Medical, and Executive", "Executive Secretaries and Executive Administrative Assistants"],
  "administrative assistant": ["Secretaries and Administrative Assistants, Except Legal, Medical, and Executive"],
  "executive assistant": ["Executive Secretaries and Executive Administrative Assistants"],
  "receptionist": ["Receptionists and Information Clerks"],
  "front desk": ["Receptionists and Information Clerks", "Hotel, Motel, and Resort Desk Clerks"],
  "office clerk": ["Office Clerks, General"],
  "file clerk": ["File Clerks"],
  "data entry": ["Data Entry Keyers"],
  "customer service": ["Customer Service Representatives"],
  "call center": ["Customer Service Representatives", "Telemarketers"],
  "dispatcher": ["Dispatchers, Except Police, Fire, and Ambulance"],

  // Engineering (non-software)
  "mechanical engineer": ["Mechanical Engineers"],
  "electrical engineer": ["Electrical Engineers"],
  "civil engineer": ["Civil Engineers"],
  "chemical engineer": ["Chemical Engineers"],
  "aerospace engineer": ["Aerospace Engineers"],
  "biomedical engineer": ["Bioengineers and Biomedical Engineers"],
  "environmental engineer": ["Environmental Engineers"],
  "industrial engineer": ["Industrial Engineers"],
  "manufacturing engineer": ["Manufacturing Engineers"],
  "structural engineer": ["Civil Engineers"],
  "architect": ["Architects, Except Landscape and Naval"],
  "drafter": ["Architectural and Civil Drafters"],
  "surveyor": ["Surveyors"],

  // Trades & Skilled Labor
  "electrician": ["Electricians"],
  "plumber": ["Plumbers, Pipefitters, and Steamfitters"],
  "carpenter": ["Carpenters"],
  "welder": ["Welders, Cutters, Solderers, and Brazers"],
  "mechanic": ["Automotive Service Technicians and Mechanics"],
  "auto mechanic": ["Automotive Service Technicians and Mechanics"],
  "hvac technician": ["Heating, Air Conditioning, and Refrigeration Mechanics and Installers"],
  "hvac": ["Heating, Air Conditioning, and Refrigeration Mechanics and Installers"],
  "painter": ["Painters, Construction and Maintenance"],
  "roofer": ["Roofers"],
  "mason": ["Brickmasons and Blockmasons"],
  "ironworker": ["Structural Iron and Steel Workers"],
  "crane operator": ["Crane and Tower Operators"],
  "forklift operator": ["Industrial Truck and Tractor Operators"],
  "truck driver": ["Heavy and Tractor-Trailer Truck Drivers", "Light Truck Drivers"],
  "trucker": ["Heavy and Tractor-Trailer Truck Drivers"],
  "delivery driver": ["Light Truck Drivers", "Driver/Sales Workers"],
  "bus driver": ["Bus Drivers, Transit and Intercity", "Bus Drivers, School"],
  "taxi driver": ["Taxi Drivers"],
  "uber driver": ["Taxi Drivers"],
  "lyft driver": ["Taxi Drivers"],
  "pilot": ["Airline Pilots, Copilots, and Flight Engineers", "Commercial Pilots"],
  "flight attendant": ["Flight Attendants"],

  // Creative & Media
  "designer": ["Graphic Designers", "Web and Digital Interface Designers"],
  "photographer": ["Photographers"],
  "videographer": ["Camera Operators, Television, Video, and Film"],
  "editor": ["Film and Video Editors", "Editors"],
  "journalist": ["Reporters and Correspondents"],
  "reporter": ["Reporters and Correspondents"],
  "writer": ["Writers and Authors"],
  "author": ["Writers and Authors"],
  "animator": ["Special Effects Artists and Animators"],
  "illustrator": ["Fine Artists, Including Painters, Sculptors, and Illustrators"],
  "musician": ["Musicians and Singers"],
  "actor": ["Actors"],
  "producer": ["Producers and Directors"],
  "director of photography": ["Camera Operators, Television, Video, and Film"],
  "sound engineer": ["Audio and Video Technicians", "Sound Engineering Technicians"],
  "interior designer": ["Interior Designers"],
  "fashion designer": ["Fashion Designers"],

  // Food & Hospitality
  "chef": ["Chefs and Head Cooks"],
  "cook": ["Cooks, Restaurant", "Cooks, Institution and Cafeteria"],
  "sous chef": ["Chefs and Head Cooks", "Cooks, Restaurant"],
  "bartender": ["Bartenders"],
  "waiter": ["Waiters and Waitresses"],
  "waitress": ["Waiters and Waitresses"],
  "server": ["Waiters and Waitresses"],
  "barista": ["Food Preparation Workers"],
  "baker": ["Bakers"],
  "host": ["Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop"],
  "hostess": ["Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop"],
  "dishwasher": ["Dishwashers"],
  "housekeeper": ["Maids and Housekeeping Cleaners"],
  "janitor": ["Janitors and Cleaners, Except Maids and Housekeeping Cleaners"],
  "custodian": ["Janitors and Cleaners, Except Maids and Housekeeping Cleaners"],
  "concierge": ["Concierges"],

  // Logistics & Supply Chain
  "supply chain manager": ["Supply Chain Managers"],
  "logistics coordinator": ["Logisticians", "Logistics Analysts"],
  "logistics manager": ["Logisticians", "Transportation, Storage, and Distribution Managers"],
  "procurement specialist": ["Purchasing Agents, Except Wholesale, Retail, and Farm Products"],
  "buyer": ["Purchasing Agents, Except Wholesale, Retail, and Farm Products"],
  "purchasing agent": ["Purchasing Agents, Except Wholesale, Retail, and Farm Products"],
  "inventory manager": ["Logisticians", "Production, Planning, and Expediting Clerks"],
  "shipping clerk": ["Shipping, Receiving, and Inventory Clerks"],

  // Science & Research
  "researcher": ["Survey Researchers", "Natural Sciences Managers"],
  "scientist": ["Natural Sciences Managers"],
  "biologist": ["Biological Scientists, All Other", "Microbiologists"],
  "chemist": ["Chemists"],
  "physicist": ["Physicists"],
  "geologist": ["Geoscientists, Except Hydrologists and Geographers"],
  "environmental scientist": ["Environmental Scientists and Specialists, Including Health"],
  "lab technician": ["Medical and Clinical Laboratory Technicians", "Chemical Technicians"],

  // Security & Law Enforcement
  "security guard": ["Security Guards"],
  "police officer": ["Police and Sheriff's Patrol Officers"],
  "cop": ["Police and Sheriff's Patrol Officers"],
  "detective": ["Detectives and Criminal Investigators"],
  "firefighter": ["Firefighters"],
  "corrections officer": ["Correctional Officers and Jailers"],
  "probation officer": ["Probation Officers and Correctional Treatment Specialists"],

  // Consulting
  "consultant": ["Management Analysts"],
  "management consultant": ["Management Analysts"],
  "strategy consultant": ["Management Analysts"],
  "it consultant": ["Computer Systems Analysts", "Management Analysts"],
};

// Given a search query, return expanded search terms including alias matches
export function expandSearchQuery(query: string): string[] {
  const q = query.toLowerCase().trim();
  const expansions: Set<string> = new Set();

  // Check each alias
  for (const [alias, titles] of Object.entries(JOB_ALIASES)) {
    if (alias.includes(q) || q.includes(alias)) {
      for (const title of titles) {
        expansions.add(title.toLowerCase());
      }
    }
  }

  return Array.from(expansions);
}
