-- Escape the Permanent Underclass - Database Schema

-- Jobs table: core occupation data from O*NET/BLS
CREATE TABLE IF NOT EXISTS jobs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  onet_code VARCHAR(10) UNIQUE,                    -- O*NET SOC code (e.g., "15-1252.00")
  title VARCHAR(255) NOT NULL,                      -- Job title
  title_aliases TEXT[],                             -- Alternative titles for search
  category VARCHAR(100),                            -- Broad category (e.g., "Technology", "Finance")
  description TEXT,                                 -- Job description

  -- Risk scoring components (1-10 scale)
  ai_risk_score DECIMAL(3,1),                       -- Overall AI replacement risk
  task_automation_score DECIMAL(3,1),               -- % of tasks automatable
  cognitive_exposure_score DECIMAL(3,1),             -- Exposure to AI cognitive capabilities
  physical_requirement_score DECIMAL(3,1),           -- Physical tasks (lower = more physical = safer)
  creativity_score DECIMAL(3,1),                     -- Creative/novel thinking required
  social_intelligence_score DECIMAL(3,1),            -- Human interaction/empathy required
  regulatory_barrier_score DECIMAL(3,1),             -- Regulatory protection level

  -- Labor market data
  median_salary INTEGER,                             -- Median annual salary USD
  employment_count INTEGER,                          -- Total US employment
  growth_projection DECIMAL(4,1),                    -- 10-year growth projection %

  -- Metadata
  data_source VARCHAR(50) DEFAULT 'onet',
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Reports table: purchased reports
CREATE TABLE IF NOT EXISTS reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  job_id UUID REFERENCES jobs(id),
  email VARCHAR(255) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,                -- Unique URL slug for web report

  -- Report content (generated by LLM)
  risk_score DECIMAL(3,1) NOT NULL,
  executive_summary TEXT,
  task_analysis JSONB,                              -- Detailed task-by-task breakdown
  career_pivot_plan JSONB,                          -- Personalized career recommendations
  skills_roadmap JSONB,                             -- Skills to develop
  asset_guidance JSONB,                             -- Asset positioning guidance
  industry_outlook TEXT,

  -- Payment
  stripe_payment_id VARCHAR(255),
  amount_paid INTEGER,                              -- cents

  -- Status
  status VARCHAR(20) DEFAULT 'pending',             -- pending, generating, completed, failed
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- X/Twitter feed cache
CREATE TABLE IF NOT EXISTS x_feed_cache (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id VARCHAR(50) UNIQUE,
  author_handle VARCHAR(100),
  author_name VARCHAR(255),
  content TEXT,
  engagement_score INTEGER,                         -- likes + retweets + replies
  topics TEXT[],                                    -- matched topics
  posted_at TIMESTAMP WITH TIME ZONE,
  cached_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_jobs_title ON jobs USING gin(to_tsvector('english', title));
CREATE INDEX IF NOT EXISTS idx_jobs_category ON jobs(category);
CREATE INDEX IF NOT EXISTS idx_jobs_risk_score ON jobs(ai_risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_reports_slug ON reports(slug);
CREATE INDEX IF NOT EXISTS idx_reports_email ON reports(email);
CREATE INDEX IF NOT EXISTS idx_x_feed_posted ON x_feed_cache(posted_at DESC);

-- Enable Row Level Security
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE x_feed_cache ENABLE ROW LEVEL SECURITY;

-- Policies: jobs are publicly readable
CREATE POLICY "Jobs are viewable by everyone" ON jobs
  FOR SELECT USING (true);

-- Reports are only viewable by the email owner (or via public slug)
CREATE POLICY "Reports viewable by slug" ON reports
  FOR SELECT USING (true);

-- X feed is publicly readable
CREATE POLICY "X feed is viewable by everyone" ON x_feed_cache
  FOR SELECT USING (true);
